research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst


brew_task:
  description: >
    Review the context you got and give brewing suggestion.
    Make sure the suggestion is detailed and contains any and all relevant information.
  expected_output: >
    A brewing recipe with detailed factos. Including water temprature, how many section of brewing, 
    each section's time of brewing, whether to water in a circular pattern or not.
    Formatted as markdown without '```'
  agent: barista

intro_task:
  description: >
    Using the following user preference and background, write a concise first-person self introduction as if you are the user.
    Include relevant technical background, education, internships, notable projects/papers, and personal hobbies if fitting.
    Keep the tone professional yet personable. The current year is {current_year}.
    User preference and bio:
    {user_preference}
  expected_output: >
    A polished self introduction in first person, 2-4 paragraphs, suitable for a personal website or professional profile. Formatted as markdown without '```'.
  agent: reporting_analyst
